<a href="https://colab.research.google.com/github/KaterynaSiniuta/ML-Hillel/blob/main/HW_2_NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Import library
import numpy as np

from numpy import pi

**ДЗ 2. NUMPY**

Dataset - https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data



Завдання:

Знайти в датасеті таргет та видалити цю колонку з датасету (видаляти за індексом)
Перетворити колонки, що залишились в 2D масив (або впевнитись, що це уже 2D масив)
Порахувати mean, median, standard deviation для 1-ї колонки
Вставити 20 значень np.nan на випадкові позиції в масиві (при використанні звичайного рандому можуть накластись позиції, тому знайти рішення, яке гарантує 20 унікальних позицій)
Знайти позиції вставлених значень np.nan в 1-й колонці
Відфільтрувати массив за умовою: значення в 3-й колонці > 1.5 та значения в 1-й колонці < 5.0 (зберегти у іншу змінну)
Замінити всі значення np.nan на 0
Порахувати всі унікальні значення в массиві та вивести їх разом із кількістю
Розбити масив по вертикалі на 2 рівні частини (не використовувати абсолютні числа, мають бути два массиви по 4 колонки)
Відсортувати обидва массиви по 1-й колонці: 1-й за збільшенням, 2-й за зменшенням
Зібрати обидва массиви в одне ціле
Знайти найбільш часто повторюване значення в массиві
Написати функцію, яка б множила всі значення в колонці, які менше середнього значения в цій колонці, на 2, і ділила інші значення на 4.
Застосувати отриману функцію до 3-ї колонки

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
a =np.genfromtxt('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', dtype=float, delimiter=',', usecols=(0,1,2,3))

In [ ]:
a.shape

(150, 4)

In [ ]:
a.ndim

2

In [ ]:
type(a)

numpy.ndarray

In [ ]:
median_fisrt_column = np.median(a[:,0])
mean_fisrt_column = np.mean(a[:,0])
std_fisrt_column = np.std(a[:,0])
print (median_fisrt_column, mean_fisrt_column, std_fisrt_column)

5.8 5.843333333333334 0.8253012917851409


In [ ]:
a.ravel()[np.random.choice(a.size, size=20, replace=False)] = np.nan

In [ ]:
num_nan = np.isnan(a).sum()
print(num_nan)

20


In [ ]:
nan_indices = np.where(np.isnan(a[:, 0]))[0]
print(nan_indices)

[10 47 98]


In [ ]:
filtered_a = a[(a[:, 2] > 1.5) & (a[:, 0] < 5.0)]

In [ ]:
a[np.isnan(a)] = 0

In [ ]:
values, counts = np.unique(a, return_counts=True)
print(np.array(list(zip(values, counts))))

[[ 0.  20. ]
 [ 0.1  6. ]
 [ 0.2 27. ]
 [ 0.3  6. ]
 [ 0.4  7. ]
 [ 0.5  1. ]
 [ 0.6  1. ]
 [ 1.   8. ]
 [ 1.1  4. ]
 [ 1.2  7. ]
 [ 1.3 20. ]
 [ 1.4 19. ]
 [ 1.5 23. ]
 [ 1.6 10. ]
 [ 1.7  6. ]
 [ 1.8 12. ]
 [ 1.9  6. ]
 [ 2.   7. ]
 [ 2.1  6. ]
 [ 2.2  6. ]
 [ 2.3 12. ]
 [ 2.4  6. ]
 [ 2.5 11. ]
 [ 2.6  4. ]
 [ 2.7  9. ]
 [ 2.8 14. ]
 [ 2.9 10. ]
 [ 3.  24. ]
 [ 3.1 11. ]
 [ 3.2 13. ]
 [ 3.3  8. ]
 [ 3.4 12. ]
 [ 3.5  8. ]
 [ 3.6  4. ]
 [ 3.7  4. ]
 [ 3.8  7. ]
 [ 3.9  5. ]
 [ 4.   6. ]
 [ 4.1  4. ]
 [ 4.2  5. ]
 [ 4.3  3. ]
 [ 4.4  8. ]
 [ 4.5  9. ]
 [ 4.6  6. ]
 [ 4.7  7. ]
 [ 4.8  9. ]
 [ 4.9 10. ]
 [ 5.  14. ]
 [ 5.1 15. ]
 [ 5.2  6. ]
 [ 5.3  3. ]
 [ 5.4  7. ]
 [ 5.5 10. ]
 [ 5.6 12. ]
 [ 5.7 11. ]
 [ 5.8 10. ]
 [ 5.9  5. ]
 [ 6.   7. ]
 [ 6.1  9. ]
 [ 6.2  4. ]
 [ 6.3 10. ]
 [ 6.4  8. ]
 [ 6.5  5. ]
 [ 6.6  3. ]
 [ 6.7  9. ]
 [ 6.8  3. ]
 [ 6.9  5. ]
 [ 7.   1. ]
 [ 7.1  1. ]
 [ 7.2  3. ]
 [ 7.3  1. ]
 [ 7.4  1. ]
 [ 7.6  1. ]
 [ 7.7  4. ]
 [ 7.9  1. ]]


In [ ]:
a1, a2 = np.vsplit(a, 2)

print("Перша частина масиву:")
print(a1)

print("Друга частина масиву:")
print(a2)

Перша частина масиву:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0. ]
 [5.  3.4 0.  0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [0.  3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 0.  0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0. ]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 0.  0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 0.  0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [0.  3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2

In [ ]:
a1_sorted = a1[a1[:, 0].argsort()]

a2_sorted = a2[a2[:, 0].argsort()[::-1]]

In [ ]:
print("Перша частина масиву:")
print(a1_sorted)

print("Друга частина масиву:")
print(a2_sorted)

Перша частина масиву:
[[0.  3.2 1.4 0.2]
 [0.  3.7 1.5 0.2]
 [4.3 3.  1.1 0.1]
 [4.4 3.2 1.3 0.2]
 [4.4 2.9 1.4 0.2]
 [4.4 3.  1.3 0.2]
 [4.5 2.3 1.3 0.3]
 [4.6 3.4 1.4 0. ]
 [4.6 3.1 1.5 0.2]
 [4.6 3.6 1.  0.2]
 [4.7 3.2 1.6 0.2]
 [4.7 3.2 1.3 0.2]
 [4.8 3.4 0.  0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.8 3.1 1.6 0.2]
 [4.8 3.  1.4 0.3]
 [4.9 3.1 1.5 0.1]
 [4.9 2.4 3.3 1. ]
 [4.9 3.1 1.5 0.1]
 [4.9 3.  1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.  3.5 0.  0.6]
 [5.  3.3 1.4 0.2]
 [5.  3.4 0.  0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.  3.5 1.3 0.3]
 [5.  2.  3.5 1. ]
 [5.  3.6 1.4 0.2]
 [5.1 3.8 1.9 0.4]
 [5.1 3.4 0.  0.2]
 [5.1 3.8 1.6 0.2]
 [5.1 3.5 1.4 0.2]
 [5.1 3.3 1.7 0.5]
 [5.1 3.7 1.5 0.4]
 [5.1 3.8 1.5 0.3]
 [5.1 3.5 1.4 0.3]
 [5.2 4.1 1.5 0.1]
 [5.2 3.4 1.4 0. ]
 [5.2 3.5 1.5 0.2]
 [5.2 2.7 3.9 1.4]
 [5.3 3.7 1.5 0.2]
 [5.4 3.4 1.5 0.4]
 [5.4 3.4 1.7 0.2]
 [5.4 3.9 1.3 0.4]
 [5.4 3.9 1.7 0.4]
 [5.5 3.5 1.3 0.2]
 [5.5 4.2 1.4 0.2]
 [5.5 2.3 4.  1.3]
 [5.6 2.5

In [ ]:
result = np.concatenate((a1_sorted, a2_sorted), axis=0)

In [ ]:
print(result)

[[0.  3.2 1.4 0.2]
 [0.  3.7 1.5 0.2]
 [4.3 3.  1.1 0.1]
 [4.4 3.2 1.3 0.2]
 [4.4 2.9 1.4 0.2]
 [4.4 3.  1.3 0.2]
 [4.5 2.3 1.3 0.3]
 [4.6 3.4 1.4 0. ]
 [4.6 3.1 1.5 0.2]
 [4.6 3.6 1.  0.2]
 [4.7 3.2 1.6 0.2]
 [4.7 3.2 1.3 0.2]
 [4.8 3.4 0.  0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.8 3.1 1.6 0.2]
 [4.8 3.  1.4 0.3]
 [4.9 3.1 1.5 0.1]
 [4.9 2.4 3.3 1. ]
 [4.9 3.1 1.5 0.1]
 [4.9 3.  1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.  3.5 0.  0.6]
 [5.  3.3 1.4 0.2]
 [5.  3.4 0.  0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.  3.5 1.3 0.3]
 [5.  2.  3.5 1. ]
 [5.  3.6 1.4 0.2]
 [5.1 3.8 1.9 0.4]
 [5.1 3.4 0.  0.2]
 [5.1 3.8 1.6 0.2]
 [5.1 3.5 1.4 0.2]
 [5.1 3.3 1.7 0.5]
 [5.1 3.7 1.5 0.4]
 [5.1 3.8 1.5 0.3]
 [5.1 3.5 1.4 0.3]
 [5.2 4.1 1.5 0.1]
 [5.2 3.4 1.4 0. ]
 [5.2 3.5 1.5 0.2]
 [5.2 2.7 3.9 1.4]
 [5.3 3.7 1.5 0.2]
 [5.4 3.4 1.5 0.4]
 [5.4 3.4 1.7 0.2]
 [5.4 3.9 1.3 0.4]
 [5.4 3.9 1.7 0.4]
 [5.5 3.5 1.3 0.2]
 [5.5 4.2 1.4 0.2]
 [5.5 2.3 4.  1.3]
 [5.6 2.5 3.9 1.1]
 [5.6 2.9 3.

In [ ]:
values2, counts2  = np.unique(result, return_counts=True)
most_frequent_value = values2[np.argmax(counts2)]

In [ ]:
print (most_frequent_value)

0.2


In [ ]:
def modify_column(column):
    column_mean = np.mean(column)
    return np.where(column < column_mean, column * 2, column / 4)

In [ ]:
result[:, 2] = modify_column(result[:, 2])

In [ ]:
print(result[:, 2])

[2.8   3.    2.2   2.6   2.8   2.6   2.6   2.8   3.    2.    3.2   2.6
 0.    3.2   2.8   3.2   2.8   3.    6.6   3.    2.8   3.    2.4   0.
 2.8   0.    3.2   3.2   2.6   7.    2.8   3.8   0.    3.2   2.8   3.4
 3.    3.    2.8   3.    2.8   3.    0.975 3.    3.    3.4   2.6   3.4
 2.6   2.8   1.    0.975 0.9   1.125 3.    1.125 3.4   1.025 2.4   1.2
 1.05  1.    1.175 1.175 1.    1.125 1.175 1.225 1.075 1.125 1.15  1.15
 1.1   1.225 1.175 1.6   0.    1.725 1.675 1.525 1.65  1.525 1.575 1.45
 1.525 0.    1.475 1.35  1.275 1.425 1.475 1.2   1.375 1.425 1.4   1.45
 1.175 1.425 1.3   1.25  1.1   1.275 1.3   1.375 1.45  1.4   1.4   1.325
 1.375 1.325 1.275 1.1   1.5   1.4   1.4   1.225 1.25  1.35  1.2   1.075
 1.4   1.15  0.    1.275 1.125 1.2   1.125 1.25  1.275 1.275 1.275 0.
 1.    0.975 1.25  7.    1.05  1.05  1.025 1.025 1.05  1.225 1.    0.925
 0.95  1.1   1.125 6.6   1.125 6.   ]
